warns:
  square:
    minLatitude: 100
    maxLatitude: 150
    minLongitude: 20
    maxLongitude: 50

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:

server:
  servlet:
    context-path: /api

