warns:
  square:
    minLatitude: 100
    maxLatitude: 800
    minLongitude: 100
    maxLongitude: 500

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:

server:
  servlet:
    context-path: /api

